
# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - $PWD/pg-data/:/var/lib/postgresql/data
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: meet.atreyo@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "80:80"
    volmlues:
      - pgadmin-data:/var/lib/pgadmin


volumes:
  # db-data:
  pgadmin-data:
